author:
  name: Björn Brockmann
  email: inbox@zusammenspiel.com
  url: www.zusammenspiel.com
name: headballooning
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
logo: null
color:
  saturation: 0.6577061
  brandStrength: 0.3245706644374877
  lightness: 0.1971326
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  rhythmicContrast: 0.8721589
typography_spectrum: 0.6308244
layout_spectrum: 0
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/44f22740-3fc9-422b-9589-3161d7eb9704.ico
